(define (problem delivery-generated-8)
  (:domain delivery)
  (:objects
    rooma roomb roomc roomd roome - room
    item35 item34 item33 item32 item31 item30 item29 item28 item27 item26 item25 item24 item23 item22 item21 item20 item19 item18 item17 item16 item15 item14 item13 item12 item11 item10 item9 item8 item7 item6 item5 item4 item3 item2 item1 - item
    bot1 bot2 bot3 - bot
    left1 mid1 right1 aux1 left2 mid2 right2 aux2 left3 mid3 right3 aux3 - arm
  )

  (:init
    (= (weight item35) 4)
    (= (weight item34) 2)
    (= (weight item33) 4)
    (= (weight item32) 4)
    (= (weight item31) 3)
    (= (weight item30) 3)
    (= (weight item29) 4)
    (= (weight item28) 4)
    (= (weight item27) 4)
    (= (weight item26) 3)
    (= (weight item25) 3)
    (= (weight item24) 2)
    (= (weight item23) 3)
    (= (weight item22) 2)
    (= (weight item21) 4)
    (= (weight item20) 1)
    (= (weight item19) 1)
    (= (weight item18) 2)
    (= (weight item17) 2)
    (= (weight item16) 4)
    (= (weight item15) 1)
    (= (weight item14) 3)
    (= (weight item13) 2)
    (= (weight item12) 3)
    (= (weight item11) 2)
    (= (weight item10) 4)
    (= (weight item9) 4)
    (= (weight item8) 2)
    (= (weight item7) 4)
    (= (weight item6) 4)
    (= (weight item5) 2)
    (= (weight item4) 2)
    (= (weight item3) 3)
    (= (weight item2) 3)
    (= (weight item1) 1)
    (= (current_load bot1) 0)
    (= (load_limit bot1) 6)
    (= (current_load bot2) 0)
    (= (load_limit bot2) 6)
    (= (current_load bot3) 0)
    (= (load_limit bot3) 6)
    (= (cost) 0)

    (at item35 rooma)
    (at item34 roomb)
    (at item33 rooma)
    (at item32 roomb)
    (at item31 rooma)
    (at item30 rooma)
    (at item29 roomb)
    (at item28 roomb)
    (at item27 rooma)
    (at item26 rooma)
    (at item25 rooma)
    (at item24 rooma)
    (at item23 rooma)
    (at item22 roomb)
    (at item21 roomb)
    (at item20 rooma)
    (at item19 roomb)
    (at item18 rooma)
    (at item17 rooma)
    (at item16 roomb)
    (at item15 rooma)
    (at item14 rooma)
    (at item13 roomb)
    (at item12 roomb)
    (at item11 roomb)
    (at item10 roomb)
    (at item9 roomb)
    (at item8 roomb)
    (at item7 roomb)
    (at item6 roomb)
    (at item5 roomb)
    (at item4 rooma)
    (at item3 roomb)
    (at item2 roomb)
    (at item1 roomb)
    (at-bot bot1 rooma)
    (at-bot bot2 rooma)
    (at-bot bot3 rooma)
    (free left1)
    (free mid1)
    (free right1)
    (free aux1)
    (free left2)
    (free mid2)
    (free right2)
    (free aux2)
    (free left3)
    (free mid3)
    (free right3)
    (free aux3)
    (mount left1 bot1)
    (mount mid1 bot1)
    (mount right1 bot1)
    (mount aux1 bot1)
    (mount left2 bot2)
    (mount mid2 bot2)
    (mount right2 bot2)
    (mount aux2 bot2)
    (mount left3 bot3)
    (mount mid3 bot3)
    (mount right3 bot3)
    (mount aux3 bot3)
    (door rooma roomb)
    (door roomb rooma)
    (door rooma roomc)
    (door roomc rooma)
    (door roomd roomb)
    (door roomb roomd)
    (door roomd roomc)
    (door roomc roomd)
    (door roomd roome)
    (door roome roomd)
  )

  (:goal (and
    (at item35 roomd)
    (at item34 rooma)
    (at item33 roomd)
    (at item32 rooma)
    (at item31 roome)
    (at item30 roomd)
    (at item29 rooma)
    (at item28 roomd)
    (at item27 roomd)
    (at item26 roomd)
    (at item25 roomd)
    (at item24 roome)
    (at item23 roomd)
    (at item22 roomd)
    (at item21 roomd)
    (at item20 roomd)
    (at item19 roomd)
    (at item18 roomd)
    (at item17 roomd)
    (at item16 rooma)
    (at item15 roomd)
    (at item14 roome)
    (at item13 roomc)
    (at item12 roomc)
    (at item11 roomc)
    (at item10 rooma)
    (at item9 roomd)
    (at item8 roomd)
    (at item7 roome)
    (at item6 roomd)
    (at item5 rooma)
    (at item4 roomd)
    (at item3 rooma)
    (at item2 roomc)
    (at item1 roomc)
  ))

  (:metric minimize (cost))
)
