(define (problem delivery-generated-1)
  (:domain delivery)
  (:objects
    rooma roomb roomc roomd roome roomf - room
    item35 item34 item33 item32 item31 item30 item29 item28 item27 item26 item25 item24 item23 item22 item21 item20 item19 item18 item17 item16 item15 item14 item13 item12 item11 item10 item9 item8 item7 item6 item5 item4 item3 item2 item1 - item
    bot1 bot2 bot3 - bot
    left1 mid1 right1 aux1 left2 mid2 right2 aux2 left3 mid3 right3 aux3 - arm
  )

  (:init
    (= (weight item35) 1)
    (= (weight item34) 4)
    (= (weight item33) 1)
    (= (weight item32) 3)
    (= (weight item31) 3)
    (= (weight item30) 2)
    (= (weight item29) 4)
    (= (weight item28) 1)
    (= (weight item27) 3)
    (= (weight item26) 4)
    (= (weight item25) 2)
    (= (weight item24) 4)
    (= (weight item23) 1)
    (= (weight item22) 4)
    (= (weight item21) 3)
    (= (weight item20) 3)
    (= (weight item19) 2)
    (= (weight item18) 1)
    (= (weight item17) 1)
    (= (weight item16) 3)
    (= (weight item15) 3)
    (= (weight item14) 3)
    (= (weight item13) 3)
    (= (weight item12) 3)
    (= (weight item11) 3)
    (= (weight item10) 4)
    (= (weight item9) 1)
    (= (weight item8) 4)
    (= (weight item7) 4)
    (= (weight item6) 2)
    (= (weight item5) 3)
    (= (weight item4) 1)
    (= (weight item3) 3)
    (= (weight item2) 2)
    (= (weight item1) 2)
    (= (current_load bot1) 0)
    (= (load_limit bot1) 6)
    (= (current_load bot2) 0)
    (= (load_limit bot2) 6)
    (= (current_load bot3) 0)
    (= (load_limit bot3) 6)
    (= (cost) 0)

    (at item35 roomc)
    (at item34 roomb)
    (at item33 rooma)
    (at item32 roomc)
    (at item31 roomb)
    (at item30 roomb)
    (at item29 roomb)
    (at item28 rooma)
    (at item27 roomb)
    (at item26 roomc)
    (at item25 roomb)
    (at item24 rooma)
    (at item23 roomb)
    (at item22 roomb)
    (at item21 roomb)
    (at item20 roomb)
    (at item19 roomc)
    (at item18 rooma)
    (at item17 roomc)
    (at item16 roomb)
    (at item15 roomc)
    (at item14 roomb)
    (at item13 roomc)
    (at item12 rooma)
    (at item11 roomb)
    (at item10 roomc)
    (at item9 rooma)
    (at item8 roomb)
    (at item7 roomc)
    (at item6 roomc)
    (at item5 roomc)
    (at item4 roomc)
    (at item3 roomb)
    (at item2 roomb)
    (at item1 roomb)
    (at-bot bot1 rooma)
    (at-bot bot2 rooma)
    (at-bot bot3 rooma)
    (free left1)
    (free mid1)
    (free right1)
    (free aux1)
    (free left2)
    (free mid2)
    (free right2)
    (free aux2)
    (free left3)
    (free mid3)
    (free right3)
    (free aux3)
    (mount left1 bot1)
    (mount mid1 bot1)
    (mount right1 bot1)
    (mount aux1 bot1)
    (mount left2 bot2)
    (mount mid2 bot2)
    (mount right2 bot2)
    (mount aux2 bot2)
    (mount left3 bot3)
    (mount mid3 bot3)
    (mount right3 bot3)
    (mount aux3 bot3)
    (door rooma roomb)
    (door roomb roomc)
    (door roomc roomd)
    (door roomd roome)
    (door roome rooma)
    (door rooma roomf)
    (door roomf roomd)
  )

  (:goal (and
    (at item35 roomb)
    (at item34 roome)
    (at item33 roome)
    (at item32 roomb)
    (at item31 roome)
    (at item30 rooma)
    (at item29 roome)
    (at item28 roomd)
    (at item27 roome)
    (at item26 roomb)
    (at item25 rooma)
    (at item24 roomc)
    (at item23 rooma)
    (at item22 rooma)
    (at item21 rooma)
    (at item20 roome)
    (at item19 roomf)
    (at item18 roomc)
    (at item17 roomf)
    (at item16 roome)
    (at item15 roomf)
    (at item14 rooma)
    (at item13 roomb)
    (at item12 roomc)
    (at item11 rooma)
    (at item10 roomb)
    (at item9 roomc)
    (at item8 roome)
    (at item7 rooma)
    (at item6 rooma)
    (at item5 roomf)
    (at item4 rooma)
    (at item3 roome)
    (at item2 rooma)
    (at item1 rooma)
  ))

  (:metric minimize (cost))
)
