(define (problem delivery-generated-9)
  (:domain delivery)
  (:objects
    rooma roomb roomc roomd roome roomf - room
    item34 item33 item32 item31 item30 item29 item28 item27 item26 item25 item24 item23 item22 item21 item20 item19 item18 item17 item16 item15 item14 item13 item12 item11 item10 item9 item8 item7 item6 item5 item4 item3 item2 item1 - item
    bot1 bot2 bot3 - bot
    left1 mid1 right1 aux1 left2 mid2 right2 aux2 left3 mid3 right3 aux3 - arm
  )

  (:init
    (= (weight item34) 3)
    (= (weight item33) 1)
    (= (weight item32) 2)
    (= (weight item31) 2)
    (= (weight item30) 2)
    (= (weight item29) 3)
    (= (weight item28) 1)
    (= (weight item27) 4)
    (= (weight item26) 2)
    (= (weight item25) 1)
    (= (weight item24) 2)
    (= (weight item23) 3)
    (= (weight item22) 2)
    (= (weight item21) 4)
    (= (weight item20) 3)
    (= (weight item19) 2)
    (= (weight item18) 2)
    (= (weight item17) 4)
    (= (weight item16) 3)
    (= (weight item15) 4)
    (= (weight item14) 4)
    (= (weight item13) 3)
    (= (weight item12) 2)
    (= (weight item11) 1)
    (= (weight item10) 3)
    (= (weight item9) 1)
    (= (weight item8) 3)
    (= (weight item7) 1)
    (= (weight item6) 4)
    (= (weight item5) 4)
    (= (weight item4) 3)
    (= (weight item3) 3)
    (= (weight item2) 1)
    (= (weight item1) 3)
    (= (current_load bot1) 0)
    (= (load_limit bot1) 6)
    (= (current_load bot2) 0)
    (= (load_limit bot2) 6)
    (= (current_load bot3) 0)
    (= (load_limit bot3) 6)
    (= (cost) 0)

    (at item34 roomb)
    (at item33 rooma)
    (at item32 roomb)
    (at item31 roomc)
    (at item30 roomb)
    (at item29 rooma)
    (at item28 roomb)
    (at item27 roomc)
    (at item26 roomb)
    (at item25 roomc)
    (at item24 rooma)
    (at item23 roomb)
    (at item22 rooma)
    (at item21 rooma)
    (at item20 roomb)
    (at item19 roomc)
    (at item18 roomb)
    (at item17 rooma)
    (at item16 roomc)
    (at item15 roomc)
    (at item14 rooma)
    (at item13 rooma)
    (at item12 roomb)
    (at item11 roomb)
    (at item10 roomb)
    (at item9 rooma)
    (at item8 rooma)
    (at item7 rooma)
    (at item6 roomb)
    (at item5 roomc)
    (at item4 rooma)
    (at item3 roomb)
    (at item2 roomb)
    (at item1 rooma)
    (at-bot bot1 rooma)
    (at-bot bot2 rooma)
    (at-bot bot3 rooma)
    (free left1)
    (free mid1)
    (free right1)
    (free aux1)
    (free left2)
    (free mid2)
    (free right2)
    (free aux2)
    (free left3)
    (free mid3)
    (free right3)
    (free aux3)
    (mount left1 bot1)
    (mount mid1 bot1)
    (mount right1 bot1)
    (mount aux1 bot1)
    (mount left2 bot2)
    (mount mid2 bot2)
    (mount right2 bot2)
    (mount aux2 bot2)
    (mount left3 bot3)
    (mount mid3 bot3)
    (mount right3 bot3)
    (mount aux3 bot3)
    (door rooma roomb)
    (door roomb roomc)
    (door roomc roomd)
    (door roomd roome)
    (door roome rooma)
    (door rooma roomf)
    (door roomf roomd)
  )

  (:goal (and
    (at item34 roome)
    (at item33 roome)
    (at item32 rooma)
    (at item31 roomf)
    (at item30 roome)
    (at item29 roome)
    (at item28 roome)
    (at item27 rooma)
    (at item26 rooma)
    (at item25 rooma)
    (at item24 roomc)
    (at item23 roome)
    (at item22 roomd)
    (at item21 roomd)
    (at item20 roome)
    (at item19 rooma)
    (at item18 roome)
    (at item17 roomc)
    (at item16 roomf)
    (at item15 rooma)
    (at item14 roome)
    (at item13 roomd)
    (at item12 roome)
    (at item11 rooma)
    (at item10 rooma)
    (at item9 roome)
    (at item8 roome)
    (at item7 roome)
    (at item6 roome)
    (at item5 roomb)
    (at item4 roome)
    (at item3 roome)
    (at item2 rooma)
    (at item1 roomd)
  ))

  (:metric minimize (cost))
)
