(define (problem delivery-generated-4)
  (:domain delivery)
  (:objects
    rooma roomb roomc roomd roome - room
    item26 item25 item24 item23 item22 item21 item20 item19 item18 item17 item16 item15 item14 item13 item12 item11 item10 item9 item8 item7 item6 item5 item4 item3 item2 item1 - item
    bot1 bot2 bot3 - bot
    left1 mid1 right1 left2 mid2 right2 left3 mid3 right3 - arm
  )

  (:init
    (= (weight item26) 1)
    (= (weight item25) 1)
    (= (weight item24) 3)
    (= (weight item23) 3)
    (= (weight item22) 2)
    (= (weight item21) 3)
    (= (weight item20) 3)
    (= (weight item19) 1)
    (= (weight item18) 3)
    (= (weight item17) 3)
    (= (weight item16) 1)
    (= (weight item15) 1)
    (= (weight item14) 2)
    (= (weight item13) 1)
    (= (weight item12) 1)
    (= (weight item11) 1)
    (= (weight item10) 3)
    (= (weight item9) 3)
    (= (weight item8) 3)
    (= (weight item7) 3)
    (= (weight item6) 3)
    (= (weight item5) 1)
    (= (weight item4) 2)
    (= (weight item3) 2)
    (= (weight item2) 2)
    (= (weight item1) 2)
    (= (current_load bot1) 0)
    (= (load_limit bot1) 6)
    (= (current_load bot2) 0)
    (= (load_limit bot2) 6)
    (= (current_load bot3) 0)
    (= (load_limit bot3) 6)
    (= (cost) 0)

    (at item26 rooma)
    (at item25 rooma)
    (at item24 rooma)
    (at item23 roomb)
    (at item22 rooma)
    (at item21 roomb)
    (at item20 rooma)
    (at item19 roomb)
    (at item18 roomb)
    (at item17 roomb)
    (at item16 roomb)
    (at item15 roomb)
    (at item14 rooma)
    (at item13 roomb)
    (at item12 rooma)
    (at item11 rooma)
    (at item10 rooma)
    (at item9 roomb)
    (at item8 roomb)
    (at item7 rooma)
    (at item6 roomb)
    (at item5 roomb)
    (at item4 rooma)
    (at item3 roomb)
    (at item2 rooma)
    (at item1 rooma)
    (at-bot bot1 rooma)
    (at-bot bot2 rooma)
    (at-bot bot3 rooma)
    (free left1)
    (free mid1)
    (free right1)
    (free left2)
    (free mid2)
    (free right2)
    (free left3)
    (free mid3)
    (free right3)
    (mount left1 bot1)
    (mount mid1 bot1)
    (mount right1 bot1)
    (mount left2 bot2)
    (mount mid2 bot2)
    (mount right2 bot2)
    (mount left3 bot3)
    (mount mid3 bot3)
    (mount right3 bot3)
    (door rooma roomb)
    (door roomb rooma)
    (door rooma roomc)
    (door roomc rooma)
    (door roomd roomb)
    (door roomb roomd)
    (door roomd roomc)
    (door roomc roomd)
    (door roomd roome)
    (door roome roomd)
  )

  (:goal (and
    (at item26 roomd)
    (at item25 roome)
    (at item24 roome)
    (at item23 rooma)
    (at item22 roome)
    (at item21 roomc)
    (at item20 roomd)
    (at item19 rooma)
    (at item18 roome)
    (at item17 roome)
    (at item16 roomd)
    (at item15 roomc)
    (at item14 roome)
    (at item13 roomd)
    (at item12 roomd)
    (at item11 roomd)
    (at item10 roomd)
    (at item9 roomd)
    (at item8 roomd)
    (at item7 roome)
    (at item6 roomd)
    (at item5 roomd)
    (at item4 roome)
    (at item3 roomd)
    (at item2 roome)
    (at item1 roomd)
  ))

  (:metric minimize (cost))
)
