(define (problem delivery-generated-7)
  (:domain delivery)
  (:objects
    rooma roomb roomc roomd - room
    item13 item12 item11 item10 item9 item8 item7 item6 item5 item4 item3 item2 item1 - item
    bot1 bot2 - bot
    left1 mid1 left2 mid2 - arm
  )

  (:init
    (= (weight item13) 1)
    (= (weight item12) 1)
    (= (weight item11) 1)
    (= (weight item10) 2)
    (= (weight item9) 2)
    (= (weight item8) 1)
    (= (weight item7) 1)
    (= (weight item6) 1)
    (= (weight item5) 2)
    (= (weight item4) 2)
    (= (weight item3) 2)
    (= (weight item2) 2)
    (= (weight item1) 1)
    (= (current_load bot1) 0)
    (= (load_limit bot1) 5)
    (= (current_load bot2) 0)
    (= (load_limit bot2) 5)
    (= (cost) 0)

    (at item13 roomb)
    (at item12 roomb)
    (at item11 roomb)
    (at item10 rooma)
    (at item9 rooma)
    (at item8 roomb)
    (at item7 rooma)
    (at item6 roomb)
    (at item5 roomb)
    (at item4 rooma)
    (at item3 rooma)
    (at item2 rooma)
    (at item1 roomb)
    (at-bot bot1 rooma)
    (at-bot bot2 rooma)
    (free left1)
    (free mid1)
    (free left2)
    (free mid2)
    (mount left1 bot1)
    (mount mid1 bot1)
    (mount left2 bot2)
    (mount mid2 bot2)
    (door rooma roomb)
    (door roomb rooma)
    (door rooma roomc)
    (door roomc rooma)
    (door roomd roomb)
    (door roomb roomd)
    (door roomd roomc)
    (door roomc roomd)
  )

  (:goal (and
    (at item13 roomc)
    (at item12 roomc)
    (at item11 roomd)
    (at item10 roomc)
    (at item9 roomb)
    (at item8 roomd)
    (at item7 roomb)
    (at item6 roomd)
    (at item5 roomd)
    (at item4 roomd)
    (at item3 roomd)
    (at item2 roomd)
    (at item1 roomd)
  ))

  (:metric minimize (cost))
)
