(define (problem delivery-generated-3)
  (:domain delivery)
  (:objects
    rooma roomb roomc roomd - room
    item18 item17 item16 item15 item14 item13 item12 item11 item10 item9 item8 item7 item6 item5 item4 item3 item2 item1 - item
    bot1 bot2 - bot
    left1 mid1 right1 left2 mid2 right2 - arm
  )

  (:init
    (= (weight item18) 2)
    (= (weight item17) 3)
    (= (weight item16) 2)
    (= (weight item15) 3)
    (= (weight item14) 1)
    (= (weight item13) 2)
    (= (weight item12) 1)
    (= (weight item11) 1)
    (= (weight item10) 1)
    (= (weight item9) 1)
    (= (weight item8) 1)
    (= (weight item7) 1)
    (= (weight item6) 1)
    (= (weight item5) 3)
    (= (weight item4) 3)
    (= (weight item3) 3)
    (= (weight item2) 3)
    (= (weight item1) 2)
    (= (current_load bot1) 0)
    (= (load_limit bot1) 5)
    (= (current_load bot2) 0)
    (= (load_limit bot2) 5)
    (= (cost) 0)

    (at item18 roomb)
    (at item17 rooma)
    (at item16 roomb)
    (at item15 roomb)
    (at item14 rooma)
    (at item13 roomb)
    (at item12 rooma)
    (at item11 roomb)
    (at item10 rooma)
    (at item9 rooma)
    (at item8 rooma)
    (at item7 rooma)
    (at item6 rooma)
    (at item5 rooma)
    (at item4 rooma)
    (at item3 roomb)
    (at item2 rooma)
    (at item1 roomb)
    (at-bot bot1 rooma)
    (at-bot bot2 rooma)
    (free left1)
    (free mid1)
    (free right1)
    (free left2)
    (free mid2)
    (free right2)
    (mount left1 bot1)
    (mount mid1 bot1)
    (mount right1 bot1)
    (mount left2 bot2)
    (mount mid2 bot2)
    (mount right2 bot2)
    (door rooma roomb)
    (door roomb rooma)
    (door rooma roomc)
    (door roomc rooma)
    (door roomd roomb)
    (door roomb roomd)
    (door roomd roomc)
    (door roomc roomd)
  )

  (:goal (and
    (at item18 roomc)
    (at item17 roomb)
    (at item16 roomd)
    (at item15 roomd)
    (at item14 roomb)
    (at item13 roomc)
    (at item12 roomb)
    (at item11 rooma)
    (at item10 roomc)
    (at item9 roomc)
    (at item8 roomc)
    (at item7 roomb)
    (at item6 roomb)
    (at item5 roomd)
    (at item4 roomd)
    (at item3 roomd)
    (at item2 roomc)
    (at item1 rooma)
  ))

  (:metric minimize (cost))
)
