(define (problem instance_9)
  (:domain fo-counters)
  (:objects
    c0 c1 c2 c3 c4 c5 c6 c7 c8 c9 - counter
  )

  (:init
    (= (max_int) 40)
    (= (value c0) 9)
    (= (value c1) 31)
    (= (value c2) 32)
    (= (value c3) 18)
    (= (value c4) 34)
    (= (value c5) 1)
    (= (value c6) 36)
    (= (value c7) 1)
    (= (value c8) 30)
    (= (value c9) 39)

    (= (rate_value c0) 0)
    (= (rate_value c1) 0)
    (= (rate_value c2) 0)
    (= (rate_value c3) 0)
    (= (rate_value c4) 0)
    (= (rate_value c5) 0)
    (= (rate_value c6) 0)
    (= (rate_value c7) 0)
    (= (rate_value c8) 0)
    (= (rate_value c9) 0)
    (= (total-cost) 0)
  )

  (:goal (and
    (<= (+ (value c4) 1) (value c7))
    (<= (+ (value c7) 1) (value c3))
    (<= (+ (value c3) 1) (value c5))
    (<= (+ (value c5) 1) (value c8))
    (<= (+ (value c8) 1) (value c9))
    (<= (+ (value c9) 1) (value c2))
    (<= (+ (value c2) 1) (value c1))
    (<= (+ (value c1) 1) (value c0))
    (<= (+ (value c0) 1) (value c6))
  ))
  (:metric minimize (total-cost))
)
