(define (problem instance_20_12_4_6)
  (:domain mt-block-grouping)
  (:objects
    b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12 - block
  )

  (:init
    (= (x b1) 2)
    (= (y b1) 2)
    (= (x b2) 12)
    (= (y b2) 19)
    (= (x b3) 11)
    (= (y b3) 4)
    (= (x b4) 12)
    (= (y b4) 4)
    (= (x b5) 19)
    (= (y b5) 5)
    (= (x b6) 18)
    (= (y b6) 13)
    (= (x b7) 2)
    (= (y b7) 6)
    (= (x b8) 15)
    (= (y b8) 9)
    (= (x b9) 4)
    (= (y b9) 11)
    (= (x b10) 12)
    (= (y b10) 13)
    (= (x b11) 11)
    (= (y b11) 6)
    (= (x b12) 18)
    (= (y b12) 15)
    (= (max_x) 20 )
    (= (min_x) 1 )
    (= (max_y) 20 )
    (= (min_y) 1 )
  )

  (:goal (and 
    (or (not (= (x b1) (x b2))) (not (= (y b1) (y b2))))
    (or (not (= (x b1) (x b3))) (not (= (y b1) (y b3))))
    (or (not (= (x b1) (x b4))) (not (= (y b1) (y b4))))
    (or (not (= (x b1) (x b5))) (not (= (y b1) (y b5))))
    (or (not (= (x b1) (x b6))) (not (= (y b1) (y b6))))
    (or (not (= (x b1) (x b7))) (not (= (y b1) (y b7))))
    (or (not (= (x b1) (x b8))) (not (= (y b1) (y b8))))
    (or (not (= (x b1) (x b9))) (not (= (y b1) (y b9))))
    (= (x b1) (x b10))
    (= (y b1) (y b10))
    (or (not (= (x b1) (x b11))) (not (= (y b1) (y b11))))
    (= (x b1) (x b12))
    (= (y b1) (y b12))
    (or (not (= (x b2) (x b3))) (not (= (y b2) (y b3))))
    (= (x b2) (x b4))
    (= (y b2) (y b4))
    (= (x b2) (x b5))
    (= (y b2) (y b5))
    (or (not (= (x b2) (x b6))) (not (= (y b2) (y b6))))
    (or (not (= (x b2) (x b7))) (not (= (y b2) (y b7))))
    (or (not (= (x b2) (x b8))) (not (= (y b2) (y b8))))
    (or (not (= (x b2) (x b9))) (not (= (y b2) (y b9))))
    (or (not (= (x b2) (x b10))) (not (= (y b2) (y b10))))
    (or (not (= (x b2) (x b11))) (not (= (y b2) (y b11))))
    (or (not (= (x b2) (x b12))) (not (= (y b2) (y b12))))
    (or (not (= (x b3) (x b4))) (not (= (y b3) (y b4))))
    (or (not (= (x b3) (x b5))) (not (= (y b3) (y b5))))
    (or (not (= (x b3) (x b6))) (not (= (y b3) (y b6))))
    (or (not (= (x b3) (x b7))) (not (= (y b3) (y b7))))
    (or (not (= (x b3) (x b8))) (not (= (y b3) (y b8))))
    (= (x b3) (x b9))
    (= (y b3) (y b9))
    (or (not (= (x b3) (x b10))) (not (= (y b3) (y b10))))
    (= (x b3) (x b11))
    (= (y b3) (y b11))
    (or (not (= (x b3) (x b12))) (not (= (y b3) (y b12))))
    (= (x b4) (x b5))
    (= (y b4) (y b5))
    (or (not (= (x b4) (x b6))) (not (= (y b4) (y b6))))
    (or (not (= (x b4) (x b7))) (not (= (y b4) (y b7))))
    (or (not (= (x b4) (x b8))) (not (= (y b4) (y b8))))
    (or (not (= (x b4) (x b9))) (not (= (y b4) (y b9))))
    (or (not (= (x b4) (x b10))) (not (= (y b4) (y b10))))
    (or (not (= (x b4) (x b11))) (not (= (y b4) (y b11))))
    (or (not (= (x b4) (x b12))) (not (= (y b4) (y b12))))
    (or (not (= (x b5) (x b6))) (not (= (y b5) (y b6))))
    (or (not (= (x b5) (x b7))) (not (= (y b5) (y b7))))
    (or (not (= (x b5) (x b8))) (not (= (y b5) (y b8))))
    (or (not (= (x b5) (x b9))) (not (= (y b5) (y b9))))
    (or (not (= (x b5) (x b10))) (not (= (y b5) (y b10))))
    (or (not (= (x b5) (x b11))) (not (= (y b5) (y b11))))
    (or (not (= (x b5) (x b12))) (not (= (y b5) (y b12))))
    (= (x b6) (x b7))
    (= (y b6) (y b7))
    (= (x b6) (x b8))
    (= (y b6) (y b8))
    (or (not (= (x b6) (x b9))) (not (= (y b6) (y b9))))
    (or (not (= (x b6) (x b10))) (not (= (y b6) (y b10))))
    (or (not (= (x b6) (x b11))) (not (= (y b6) (y b11))))
    (or (not (= (x b6) (x b12))) (not (= (y b6) (y b12))))
    (= (x b7) (x b8))
    (= (y b7) (y b8))
    (or (not (= (x b7) (x b9))) (not (= (y b7) (y b9))))
    (or (not (= (x b7) (x b10))) (not (= (y b7) (y b10))))
    (or (not (= (x b7) (x b11))) (not (= (y b7) (y b11))))
    (or (not (= (x b7) (x b12))) (not (= (y b7) (y b12))))
    (or (not (= (x b8) (x b9))) (not (= (y b8) (y b9))))
    (or (not (= (x b8) (x b10))) (not (= (y b8) (y b10))))
    (or (not (= (x b8) (x b11))) (not (= (y b8) (y b11))))
    (or (not (= (x b8) (x b12))) (not (= (y b8) (y b12))))
    (or (not (= (x b9) (x b10))) (not (= (y b9) (y b10))))
    (= (x b9) (x b11))
    (= (y b9) (y b11))
    (or (not (= (x b9) (x b12))) (not (= (y b9) (y b12))))
    (or (not (= (x b10) (x b11))) (not (= (y b10) (y b11))))
    (= (x b10) (x b12))
    (= (y b10) (y b12))
    (or (not (= (x b11) (x b12))) (not (= (y b11) (y b12))))
  ))
)
