(define (problem ZTRAVEL-2)
(:domain zenotravel)
(:objects
    plane1 - aircraft
    person1 person2 - person
    city0 city1 city2 city3 - city
)
(:init
    (located plane1 city2)
    (= (capacity plane1) 5357)
    (= (fuel plane1) 2500)
    (= (slow-burn plane1) 2)
    (= (fast-burn plane1) 5)
    (= (onboard plane1) 0)
    (= (zoom-limit plane1) 8)
    (located person1 city2)
    (located person2 city2)
    (= (distance city0 city0) 0)
    (= (distance city0 city1) 224)
    (= (distance city0 city2) 216)
    (= (distance city0 city3) 232)
    (= (distance city1 city0) 224)
    (= (distance city1 city1) 0)
    (= (distance city1 city2) 104)
    (= (distance city1 city3) 176)
    (= (distance city2 city0) 216)
    (= (distance city2 city1) 104)
    (= (distance city2 city2) 0)
    (= (distance city2 city3) 199)
    (= (distance city3 city0) 232)
    (= (distance city3 city1) 176)
    (= (distance city3 city2) 199)
    (= (distance city3 city3) 0)
    (= (total-fuel-used) 0)
)
(:goal (and
    (located person1 city1)
    (located person2 city1)
))
(:metric  minimize (total-fuel-used) )
)
