(define (problem ZTRAVEL-9)
(:domain zenotravel)
(:objects
    plane1 - aircraft
    person1 person2 person3 - person
    city0 city1 city2 city3 - city
)
(:init
    (located plane1 city2)
    (= (capacity plane1) 6711)
    (= (fuel plane1) 2500)
    (= (slow-burn plane1) 2)
    (= (fast-burn plane1) 3)
    (= (onboard plane1) 0)
    (= (zoom-limit plane1) 8)
    (located person1 city1)
    (located person2 city0)
    (located person3 city1)
    (= (distance city0 city0) 0)
    (= (distance city0 city1) 86)
    (= (distance city0 city2) 156)
    (= (distance city0 city3) 95)
    (= (distance city1 city0) 86)
    (= (distance city1 city1) 0)
    (= (distance city1 city2) 121)
    (= (distance city1 city3) 232)
    (= (distance city2 city0) 156)
    (= (distance city2 city1) 121)
    (= (distance city2 city2) 0)
    (= (distance city2 city3) 168)
    (= (distance city3 city0) 95)
    (= (distance city3 city1) 232)
    (= (distance city3 city2) 168)
    (= (distance city3 city3) 0)
    (= (total-fuel-used) 0)
)
(:goal (and
    (located person1 city0)
    (located person2 city1)
    (located person3 city2)
))
(:metric  minimize (total-fuel-used) )
)
