(define (problem ZTRAVEL-5)
(:domain zenotravel)
(:objects
    plane1 - aircraft
    person1 person2 person3 person4 - person
    city0 city1 city2 city3 - city
)
(:init
    (located plane1 city2)
    (= (capacity plane1) 6137)
    (= (fuel plane1) 1361)
    (= (slow-burn plane1) 6)
    (= (fast-burn plane1) 11)
    (= (onboard plane1) 0)
    (= (zoom-limit plane1) 8)
    (located person1 city1)
    (located person2 city2)
    (located person3 city0)
    (located person4 city0)
    (= (distance city0 city0) 0)
    (= (distance city0 city1) 611)
    (= (distance city0 city2) 660)
    (= (distance city0 city3) 961)
    (= (distance city1 city0) 611)
    (= (distance city1 city1) 0)
    (= (distance city1 city2) 777)
    (= (distance city1 city3) 1086)
    (= (distance city2 city0) 660)
    (= (distance city2 city1) 777)
    (= (distance city2 city2) 0)
    (= (distance city2 city3) 908)
    (= (distance city3 city0) 961)
    (= (distance city3 city1) 1086)
    (= (distance city3 city2) 908)
    (= (distance city3 city3) 0)
    (= (total-fuel-used) 0)
)
(:goal (and
    (located plane1 city0)
    (located person1 city3)
    (located person2 city3)
    (located person3 city2)
    (located person4 city1)
))
(:metric  minimize (total-fuel-used) )
)
