(define (problem ZTRAVEL-4)
(:domain zenotravel)
(:objects
    plane1 - aircraft
    person1 person2 person3 person4 - person
    city0 city1 city2 - city
)
(:init
    (located plane1 city2)
    (= (capacity plane1) 3124)
    (= (fuel plane1) 486)
    (= (slow-burn plane1) 2)
    (= (fast-burn plane1) 16)
    (= (onboard plane1) 0)
    (= (zoom-limit plane1) 6)
    (located person1 city2)
    (located person2 city2)
    (located person3 city2)
    (located person4 city2)
    (= (distance city0 city0) 0)
    (= (distance city0 city1) 702)
    (= (distance city0 city2) 691)
    (= (distance city1 city0) 702)
    (= (distance city1 city1) 0)
    (= (distance city1 city2) 1162)
    (= (distance city2 city0) 691)
    (= (distance city2 city1) 1162)
    (= (distance city2 city2) 0)
    (= (total-fuel-used) 0)
)
(:goal (and
    (located person1 city1)
    (located person2 city0)
    (located person3 city1)
    (located person4 city1)
))
(:metric  minimize (total-fuel-used) )
)
