(define (problem delivery-generated-2)
  (:domain delivery)
  (:objects
    rooma roomb roomc roomd roome - room
    item42 item41 item40 item39 item38 item37 item36 item35 item34 item33 item32 item31 item30 item29 item28 item27 item26 item25 item24 item23 item22 item21 item20 item19 item18 item17 item16 item15 item14 item13 item12 item11 item10 item9 item8 item7 item6 item5 item4 item3 item2 item1 - item
    bot1 bot2 bot3 - bot
    left1 mid1 right1 aux1 left2 mid2 right2 aux2 left3 mid3 right3 aux3 - arm
  )

  (:init
    (= (weight item42) 2)
    (= (weight item41) 1)
    (= (weight item40) 3)
    (= (weight item39) 2)
    (= (weight item38) 2)
    (= (weight item37) 2)
    (= (weight item36) 2)
    (= (weight item35) 4)
    (= (weight item34) 4)
    (= (weight item33) 4)
    (= (weight item32) 3)
    (= (weight item31) 2)
    (= (weight item30) 3)
    (= (weight item29) 3)
    (= (weight item28) 1)
    (= (weight item27) 4)
    (= (weight item26) 1)
    (= (weight item25) 2)
    (= (weight item24) 1)
    (= (weight item23) 3)
    (= (weight item22) 1)
    (= (weight item21) 1)
    (= (weight item20) 1)
    (= (weight item19) 2)
    (= (weight item18) 2)
    (= (weight item17) 2)
    (= (weight item16) 4)
    (= (weight item15) 2)
    (= (weight item14) 4)
    (= (weight item13) 1)
    (= (weight item12) 3)
    (= (weight item11) 1)
    (= (weight item10) 1)
    (= (weight item9) 4)
    (= (weight item8) 4)
    (= (weight item7) 1)
    (= (weight item6) 4)
    (= (weight item5) 4)
    (= (weight item4) 2)
    (= (weight item3) 2)
    (= (weight item2) 1)
    (= (weight item1) 4)
    (= (current_load bot1) 0)
    (= (load_limit bot1) 6)
    (= (current_load bot2) 0)
    (= (load_limit bot2) 6)
    (= (current_load bot3) 0)
    (= (load_limit bot3) 6)
    (= (cost) 0)

    (at item42 roomb)
    (at item41 roomb)
    (at item40 roomb)
    (at item39 rooma)
    (at item38 roomb)
    (at item37 rooma)
    (at item36 rooma)
    (at item35 rooma)
    (at item34 rooma)
    (at item33 roomb)
    (at item32 roomb)
    (at item31 rooma)
    (at item30 rooma)
    (at item29 roomb)
    (at item28 roomb)
    (at item27 rooma)
    (at item26 rooma)
    (at item25 rooma)
    (at item24 rooma)
    (at item23 rooma)
    (at item22 rooma)
    (at item21 rooma)
    (at item20 rooma)
    (at item19 rooma)
    (at item18 roomb)
    (at item17 rooma)
    (at item16 roomb)
    (at item15 roomb)
    (at item14 roomb)
    (at item13 rooma)
    (at item12 roomb)
    (at item11 rooma)
    (at item10 roomb)
    (at item9 roomb)
    (at item8 roomb)
    (at item7 rooma)
    (at item6 roomb)
    (at item5 roomb)
    (at item4 rooma)
    (at item3 roomb)
    (at item2 rooma)
    (at item1 rooma)
    (at-bot bot1 rooma)
    (at-bot bot2 rooma)
    (at-bot bot3 rooma)
    (free left1)
    (free mid1)
    (free right1)
    (free aux1)
    (free left2)
    (free mid2)
    (free right2)
    (free aux2)
    (free left3)
    (free mid3)
    (free right3)
    (free aux3)
    (mount left1 bot1)
    (mount mid1 bot1)
    (mount right1 bot1)
    (mount aux1 bot1)
    (mount left2 bot2)
    (mount mid2 bot2)
    (mount right2 bot2)
    (mount aux2 bot2)
    (mount left3 bot3)
    (mount mid3 bot3)
    (mount right3 bot3)
    (mount aux3 bot3)
    (door rooma roomb)
    (door roomb rooma)
    (door rooma roomc)
    (door roomc rooma)
    (door roomd roomb)
    (door roomb roomd)
    (door roomd roomc)
    (door roomc roomd)
    (door roomd roome)
    (door roome roomd)
  )

  (:goal (and
    (at item42 roome)
    (at item41 roome)
    (at item40 roome)
    (at item39 roome)
    (at item38 rooma)
    (at item37 roomd)
    (at item36 roomd)
    (at item35 roomd)
    (at item34 roomd)
    (at item33 roomd)
    (at item32 roomd)
    (at item31 roomd)
    (at item30 roome)
    (at item29 roomd)
    (at item28 roome)
    (at item27 roome)
    (at item26 roomd)
    (at item25 roomd)
    (at item24 roome)
    (at item23 roomd)
    (at item22 roomd)
    (at item21 roome)
    (at item20 roomd)
    (at item19 roome)
    (at item18 roomd)
    (at item17 roome)
    (at item16 roomc)
    (at item15 roome)
    (at item14 roome)
    (at item13 roome)
    (at item12 roomd)
    (at item11 roomd)
    (at item10 roomc)
    (at item9 roome)
    (at item8 roomd)
    (at item7 roome)
    (at item6 roomd)
    (at item5 roomd)
    (at item4 roome)
    (at item3 roomc)
    (at item2 roome)
    (at item1 roome)
  ))

  (:metric minimize (cost))
)
