(define (problem delivery-generated-7)
  (:domain delivery)
  (:objects
    rooma roomb roomc roomd roome - room
    item39 item38 item37 item36 item35 item34 item33 item32 item31 item30 item29 item28 item27 item26 item25 item24 item23 item22 item21 item20 item19 item18 item17 item16 item15 item14 item13 item12 item11 item10 item9 item8 item7 item6 item5 item4 item3 item2 item1 - item
    bot1 bot2 bot3 - bot
    left1 mid1 right1 aux1 left2 mid2 right2 aux2 left3 mid3 right3 aux3 - arm
  )

  (:init
    (= (weight item39) 3)
    (= (weight item38) 4)
    (= (weight item37) 1)
    (= (weight item36) 3)
    (= (weight item35) 3)
    (= (weight item34) 1)
    (= (weight item33) 3)
    (= (weight item32) 3)
    (= (weight item31) 1)
    (= (weight item30) 4)
    (= (weight item29) 2)
    (= (weight item28) 2)
    (= (weight item27) 3)
    (= (weight item26) 4)
    (= (weight item25) 4)
    (= (weight item24) 1)
    (= (weight item23) 3)
    (= (weight item22) 3)
    (= (weight item21) 2)
    (= (weight item20) 2)
    (= (weight item19) 3)
    (= (weight item18) 4)
    (= (weight item17) 1)
    (= (weight item16) 3)
    (= (weight item15) 2)
    (= (weight item14) 2)
    (= (weight item13) 2)
    (= (weight item12) 3)
    (= (weight item11) 3)
    (= (weight item10) 3)
    (= (weight item9) 4)
    (= (weight item8) 3)
    (= (weight item7) 2)
    (= (weight item6) 2)
    (= (weight item5) 1)
    (= (weight item4) 2)
    (= (weight item3) 2)
    (= (weight item2) 4)
    (= (weight item1) 3)
    (= (current_load bot1) 0)
    (= (load_limit bot1) 6)
    (= (current_load bot2) 0)
    (= (load_limit bot2) 6)
    (= (current_load bot3) 0)
    (= (load_limit bot3) 6)
    (= (cost) 0)

    (at item39 roomb)
    (at item38 rooma)
    (at item37 rooma)
    (at item36 roomb)
    (at item35 roomb)
    (at item34 roomb)
    (at item33 rooma)
    (at item32 roomb)
    (at item31 roomb)
    (at item30 rooma)
    (at item29 roomb)
    (at item28 roomb)
    (at item27 rooma)
    (at item26 rooma)
    (at item25 roomb)
    (at item24 roomb)
    (at item23 rooma)
    (at item22 roomb)
    (at item21 roomb)
    (at item20 roomb)
    (at item19 roomb)
    (at item18 roomb)
    (at item17 rooma)
    (at item16 roomb)
    (at item15 rooma)
    (at item14 roomb)
    (at item13 roomb)
    (at item12 roomb)
    (at item11 rooma)
    (at item10 roomb)
    (at item9 rooma)
    (at item8 roomb)
    (at item7 roomb)
    (at item6 roomb)
    (at item5 rooma)
    (at item4 rooma)
    (at item3 roomb)
    (at item2 roomb)
    (at item1 rooma)
    (at-bot bot1 rooma)
    (at-bot bot2 rooma)
    (at-bot bot3 rooma)
    (free left1)
    (free mid1)
    (free right1)
    (free aux1)
    (free left2)
    (free mid2)
    (free right2)
    (free aux2)
    (free left3)
    (free mid3)
    (free right3)
    (free aux3)
    (mount left1 bot1)
    (mount mid1 bot1)
    (mount right1 bot1)
    (mount aux1 bot1)
    (mount left2 bot2)
    (mount mid2 bot2)
    (mount right2 bot2)
    (mount aux2 bot2)
    (mount left3 bot3)
    (mount mid3 bot3)
    (mount right3 bot3)
    (mount aux3 bot3)
    (door rooma roomb)
    (door roomb rooma)
    (door rooma roomc)
    (door roomc rooma)
    (door roomd roomb)
    (door roomb roomd)
    (door roomd roomc)
    (door roomc roomd)
    (door roomd roome)
    (door roome roomd)
  )

  (:goal (and
    (at item39 roomd)
    (at item38 roomd)
    (at item37 roome)
    (at item36 roome)
    (at item35 rooma)
    (at item34 rooma)
    (at item33 roomd)
    (at item32 roome)
    (at item31 rooma)
    (at item30 roomd)
    (at item29 rooma)
    (at item28 rooma)
    (at item27 roomd)
    (at item26 roomd)
    (at item25 roomc)
    (at item24 roomd)
    (at item23 roome)
    (at item22 rooma)
    (at item21 roomd)
    (at item20 roomc)
    (at item19 roome)
    (at item18 rooma)
    (at item17 roome)
    (at item16 roomd)
    (at item15 roomd)
    (at item14 roomd)
    (at item13 rooma)
    (at item12 roome)
    (at item11 roomd)
    (at item10 roomc)
    (at item9 roome)
    (at item8 roomc)
    (at item7 roomd)
    (at item6 roome)
    (at item5 roomd)
    (at item4 roomd)
    (at item3 roomd)
    (at item2 roome)
    (at item1 roomd)
  ))

  (:metric minimize (cost))
)
