(define (problem delivery-generated-0)
  (:domain delivery)
  (:objects
    rooma roomb roomc roomd roome roomf - room
    item40 item39 item38 item37 item36 item35 item34 item33 item32 item31 item30 item29 item28 item27 item26 item25 item24 item23 item22 item21 item20 item19 item18 item17 item16 item15 item14 item13 item12 item11 item10 item9 item8 item7 item6 item5 item4 item3 item2 item1 - item
    bot1 bot2 bot3 - bot
    left1 mid1 right1 aux1 left2 mid2 right2 aux2 left3 mid3 right3 aux3 - arm
  )

  (:init
    (= (weight item40) 1)
    (= (weight item39) 1)
    (= (weight item38) 2)
    (= (weight item37) 3)
    (= (weight item36) 4)
    (= (weight item35) 1)
    (= (weight item34) 3)
    (= (weight item33) 4)
    (= (weight item32) 4)
    (= (weight item31) 1)
    (= (weight item30) 2)
    (= (weight item29) 3)
    (= (weight item28) 2)
    (= (weight item27) 4)
    (= (weight item26) 2)
    (= (weight item25) 4)
    (= (weight item24) 2)
    (= (weight item23) 4)
    (= (weight item22) 2)
    (= (weight item21) 4)
    (= (weight item20) 3)
    (= (weight item19) 4)
    (= (weight item18) 4)
    (= (weight item17) 2)
    (= (weight item16) 1)
    (= (weight item15) 4)
    (= (weight item14) 2)
    (= (weight item13) 3)
    (= (weight item12) 3)
    (= (weight item11) 1)
    (= (weight item10) 1)
    (= (weight item9) 4)
    (= (weight item8) 4)
    (= (weight item7) 3)
    (= (weight item6) 2)
    (= (weight item5) 3)
    (= (weight item4) 4)
    (= (weight item3) 1)
    (= (weight item2) 4)
    (= (weight item1) 1)
    (= (current_load bot1) 0)
    (= (load_limit bot1) 6)
    (= (current_load bot2) 0)
    (= (load_limit bot2) 6)
    (= (current_load bot3) 0)
    (= (load_limit bot3) 6)
    (= (cost) 0)

    (at item40 roomb)
    (at item39 roomb)
    (at item38 roomc)
    (at item37 rooma)
    (at item36 roomc)
    (at item35 rooma)
    (at item34 rooma)
    (at item33 rooma)
    (at item32 rooma)
    (at item31 roomc)
    (at item30 roomc)
    (at item29 roomb)
    (at item28 roomc)
    (at item27 rooma)
    (at item26 rooma)
    (at item25 roomc)
    (at item24 roomb)
    (at item23 roomc)
    (at item22 rooma)
    (at item21 roomc)
    (at item20 roomb)
    (at item19 roomc)
    (at item18 roomc)
    (at item17 rooma)
    (at item16 roomb)
    (at item15 roomb)
    (at item14 roomc)
    (at item13 roomb)
    (at item12 roomb)
    (at item11 roomb)
    (at item10 roomb)
    (at item9 rooma)
    (at item8 roomb)
    (at item7 roomb)
    (at item6 roomb)
    (at item5 roomc)
    (at item4 roomc)
    (at item3 roomc)
    (at item2 rooma)
    (at item1 roomc)
    (at-bot bot1 rooma)
    (at-bot bot2 rooma)
    (at-bot bot3 rooma)
    (free left1)
    (free mid1)
    (free right1)
    (free aux1)
    (free left2)
    (free mid2)
    (free right2)
    (free aux2)
    (free left3)
    (free mid3)
    (free right3)
    (free aux3)
    (mount left1 bot1)
    (mount mid1 bot1)
    (mount right1 bot1)
    (mount aux1 bot1)
    (mount left2 bot2)
    (mount mid2 bot2)
    (mount right2 bot2)
    (mount aux2 bot2)
    (mount left3 bot3)
    (mount mid3 bot3)
    (mount right3 bot3)
    (mount aux3 bot3)
    (door rooma roomb)
    (door roomb roomc)
    (door roomc roomd)
    (door roomd roome)
    (door roome rooma)
    (door rooma roomf)
    (door roomf roomd)
  )

  (:goal (and
    (at item40 roome)
    (at item39 roome)
    (at item38 roomf)
    (at item37 roomd)
    (at item36 rooma)
    (at item35 roomd)
    (at item34 roomc)
    (at item33 roomc)
    (at item32 roomc)
    (at item31 roomb)
    (at item30 rooma)
    (at item29 rooma)
    (at item28 roomf)
    (at item27 roomc)
    (at item26 roomc)
    (at item25 roomf)
    (at item24 rooma)
    (at item23 rooma)
    (at item22 roomc)
    (at item21 rooma)
    (at item20 roome)
    (at item19 rooma)
    (at item18 roomf)
    (at item17 roomc)
    (at item16 rooma)
    (at item15 roome)
    (at item14 rooma)
    (at item13 roome)
    (at item12 roome)
    (at item11 rooma)
    (at item10 roome)
    (at item9 roomd)
    (at item8 roome)
    (at item7 rooma)
    (at item6 rooma)
    (at item5 rooma)
    (at item4 roomf)
    (at item3 roomb)
    (at item2 roomc)
    (at item1 rooma)
  ))

  (:metric minimize (cost))
)
