(define (problem delivery-generated-6)
  (:domain delivery)
  (:objects
    rooma roomb roomc roomd roome - room
    item28 item27 item26 item25 item24 item23 item22 item21 item20 item19 item18 item17 item16 item15 item14 item13 item12 item11 item10 item9 item8 item7 item6 item5 item4 item3 item2 item1 - item
    bot1 bot2 bot3 - bot
    left1 mid1 right1 aux1 left2 mid2 right2 aux2 left3 mid3 right3 aux3 - arm
  )

  (:init
    (= (weight item28) 3)
    (= (weight item27) 2)
    (= (weight item26) 2)
    (= (weight item25) 2)
    (= (weight item24) 2)
    (= (weight item23) 2)
    (= (weight item22) 4)
    (= (weight item21) 1)
    (= (weight item20) 4)
    (= (weight item19) 2)
    (= (weight item18) 1)
    (= (weight item17) 1)
    (= (weight item16) 3)
    (= (weight item15) 1)
    (= (weight item14) 3)
    (= (weight item13) 2)
    (= (weight item12) 4)
    (= (weight item11) 3)
    (= (weight item10) 1)
    (= (weight item9) 4)
    (= (weight item8) 3)
    (= (weight item7) 3)
    (= (weight item6) 4)
    (= (weight item5) 3)
    (= (weight item4) 4)
    (= (weight item3) 2)
    (= (weight item2) 1)
    (= (weight item1) 4)
    (= (current_load bot1) 0)
    (= (load_limit bot1) 6)
    (= (current_load bot2) 0)
    (= (load_limit bot2) 6)
    (= (current_load bot3) 0)
    (= (load_limit bot3) 6)
    (= (cost) 0)

    (at item28 rooma)
    (at item27 rooma)
    (at item26 rooma)
    (at item25 roomb)
    (at item24 roomb)
    (at item23 rooma)
    (at item22 rooma)
    (at item21 roomb)
    (at item20 rooma)
    (at item19 roomb)
    (at item18 roomb)
    (at item17 rooma)
    (at item16 roomb)
    (at item15 roomb)
    (at item14 rooma)
    (at item13 roomb)
    (at item12 rooma)
    (at item11 roomb)
    (at item10 roomb)
    (at item9 roomb)
    (at item8 roomb)
    (at item7 rooma)
    (at item6 rooma)
    (at item5 roomb)
    (at item4 roomb)
    (at item3 rooma)
    (at item2 rooma)
    (at item1 rooma)
    (at-bot bot1 rooma)
    (at-bot bot2 rooma)
    (at-bot bot3 rooma)
    (free left1)
    (free mid1)
    (free right1)
    (free aux1)
    (free left2)
    (free mid2)
    (free right2)
    (free aux2)
    (free left3)
    (free mid3)
    (free right3)
    (free aux3)
    (mount left1 bot1)
    (mount mid1 bot1)
    (mount right1 bot1)
    (mount aux1 bot1)
    (mount left2 bot2)
    (mount mid2 bot2)
    (mount right2 bot2)
    (mount aux2 bot2)
    (mount left3 bot3)
    (mount mid3 bot3)
    (mount right3 bot3)
    (mount aux3 bot3)
    (door rooma roomb)
    (door roomb rooma)
    (door rooma roomc)
    (door roomc rooma)
    (door roomd roomb)
    (door roomb roomd)
    (door roomd roomc)
    (door roomc roomd)
    (door roomd roome)
    (door roome roomd)
  )

  (:goal (and
    (at item28 roomd)
    (at item27 roome)
    (at item26 roome)
    (at item25 rooma)
    (at item24 roomc)
    (at item23 roome)
    (at item22 roome)
    (at item21 roomc)
    (at item20 roomd)
    (at item19 roome)
    (at item18 rooma)
    (at item17 roomd)
    (at item16 roomd)
    (at item15 roomc)
    (at item14 roomd)
    (at item13 roomd)
    (at item12 roomd)
    (at item11 rooma)
    (at item10 roomd)
    (at item9 roomc)
    (at item8 roome)
    (at item7 roomd)
    (at item6 roome)
    (at item5 rooma)
    (at item4 roomd)
    (at item3 roomd)
    (at item2 roome)
    (at item1 roome)
  ))

  (:metric minimize (cost))
)
