(define (problem instance_10_7_3_6)
  (:domain mt-block-grouping)
  (:objects
    b1 b2 b3 b4 b5 b6 b7 - block
  )

  (:init
    (= (x b1) 6)
    (= (y b1) 9)
    (= (x b2) 6)
    (= (y b2) 1)
    (= (x b3) 6)
    (= (y b3) 7)
    (= (x b4) 2)
    (= (y b4) 6)
    (= (x b5) 2)
    (= (y b5) 6)
    (= (x b6) 1)
    (= (y b6) 7)
    (= (x b7) 6)
    (= (y b7) 8)
    (= (max_x) 10 )
    (= (min_x) 1 )
    (= (max_y) 10 )
    (= (min_y) 1 )
  )

  (:goal (and 
    (or (not (= (x b1) (x b2))) (not (= (y b1) (y b2))))
    (or (not (= (x b1) (x b3))) (not (= (y b1) (y b3))))
    (= (x b1) (x b4))
    (= (y b1) (y b4))
    (or (not (= (x b1) (x b5))) (not (= (y b1) (y b5))))
    (or (not (= (x b1) (x b6))) (not (= (y b1) (y b6))))
    (= (x b1) (x b7))
    (= (y b1) (y b7))
    (= (x b2) (x b3))
    (= (y b2) (y b3))
    (or (not (= (x b2) (x b4))) (not (= (y b2) (y b4))))
    (or (not (= (x b2) (x b5))) (not (= (y b2) (y b5))))
    (or (not (= (x b2) (x b6))) (not (= (y b2) (y b6))))
    (or (not (= (x b2) (x b7))) (not (= (y b2) (y b7))))
    (or (not (= (x b3) (x b4))) (not (= (y b3) (y b4))))
    (or (not (= (x b3) (x b5))) (not (= (y b3) (y b5))))
    (or (not (= (x b3) (x b6))) (not (= (y b3) (y b6))))
    (or (not (= (x b3) (x b7))) (not (= (y b3) (y b7))))
    (or (not (= (x b4) (x b5))) (not (= (y b4) (y b5))))
    (or (not (= (x b4) (x b6))) (not (= (y b4) (y b6))))
    (= (x b4) (x b7))
    (= (y b4) (y b7))
    (= (x b5) (x b6))
    (= (y b5) (y b6))
    (or (not (= (x b5) (x b7))) (not (= (y b5) (y b7))))
    (or (not (= (x b6) (x b7))) (not (= (y b6) (y b7))))
  ))
)
