(define (problem ZTRAVEL-3)
(:domain zenotravel)
(:objects
    plane1 - aircraft
    person1 person2 person3 - person
    city0 city1 city2 city3 - city
)
(:init
    (located plane1 city2)
    (= (capacity plane1) 4120)
    (= (fuel plane1) 2500)
    (= (slow-burn plane1) 1)
    (= (fast-burn plane1) 3)
    (= (onboard plane1) 0)
    (= (zoom-limit plane1) 5)
    (located person1 city3)
    (located person2 city3)
    (located person3 city1)
    (= (distance city0 city0) 0)
    (= (distance city0 city1) 161)
    (= (distance city0 city2) 242)
    (= (distance city0 city3) 175)
    (= (distance city1 city0) 161)
    (= (distance city1 city1) 0)
    (= (distance city1 city2) 250)
    (= (distance city1 city3) 147)
    (= (distance city2 city0) 242)
    (= (distance city2 city1) 250)
    (= (distance city2 city2) 0)
    (= (distance city2 city3) 91)
    (= (distance city3 city0) 175)
    (= (distance city3 city1) 147)
    (= (distance city3 city2) 91)
    (= (distance city3 city3) 0)
    (= (total-fuel-used) 0)
)
(:goal (and
    (located person1 city0)
    (located person2 city2)
    (located person3 city2)
))
(:metric  minimize (total-fuel-used) )
)
