(define (problem ZTRAVEL-10)
(:domain zenotravel)
(:objects
    plane1 - aircraft
    person1 person2 person3 - person
    city0 city1 city2 city3 - city
)
(:init
    (located plane1 city2)
    (= (capacity plane1) 6197)
    (= (fuel plane1) 2500)
    (= (slow-burn plane1) 2)
    (= (fast-burn plane1) 3)
    (= (onboard plane1) 0)
    (= (zoom-limit plane1) 7)
    (located person1 city2)
    (located person2 city1)
    (located person3 city2)
    (= (distance city0 city0) 0)
    (= (distance city0 city1) 144)
    (= (distance city0 city2) 145)
    (= (distance city0 city3) 177)
    (= (distance city1 city0) 144)
    (= (distance city1 city1) 0)
    (= (distance city1 city2) 181)
    (= (distance city1 city3) 194)
    (= (distance city2 city0) 145)
    (= (distance city2 city1) 181)
    (= (distance city2 city2) 0)
    (= (distance city2 city3) 84)
    (= (distance city3 city0) 177)
    (= (distance city3 city1) 194)
    (= (distance city3 city2) 84)
    (= (distance city3 city3) 0)
    (= (total-fuel-used) 0)
)
(:goal (and
    (located plane1 city1)
    (located person1 city1)
    (located person2 city0)
    (located person3 city0)
))
(:metric  minimize (total-fuel-used) )
)
