(define (problem ZTRAVEL-6)
(:domain zenotravel)
(:objects
    plane1 - aircraft
    person1 person2 - person
    city0 city1 city2 city3 - city
)
(:init
    (located plane1 city1)
    (= (capacity plane1) 6078)
    (= (fuel plane1) 2104)
    (= (slow-burn plane1) 4)
    (= (fast-burn plane1) 12)
    (= (onboard plane1) 0)
    (= (zoom-limit plane1) 5)
    (located person1 city0)
    (located person2 city1)
    (= (distance city0 city0) 0)
    (= (distance city0 city1) 755)
    (= (distance city0 city2) 700)
    (= (distance city0 city3) 776)
    (= (distance city1 city0) 755)
    (= (distance city1 city1) 0)
    (= (distance city1 city2) 985)
    (= (distance city1 city3) 711)
    (= (distance city2 city0) 700)
    (= (distance city2 city1) 985)
    (= (distance city2 city2) 0)
    (= (distance city2 city3) 891)
    (= (distance city3 city0) 776)
    (= (distance city3 city1) 711)
    (= (distance city3 city2) 891)
    (= (distance city3 city3) 0)
    (= (total-fuel-used) 0)
)
(:goal (and
    (located person1 city1)
    (located person2 city3)
))
(:metric  minimize (total-fuel-used) )
)
