(define (problem delivery-generated-4)
  (:domain delivery)
  (:objects
    rooma roomb roomc roomd roome - room
    item16 item15 item14 item13 item12 item11 item10 item9 item8 item7 item6 item5 item4 item3 item2 item1 - item
    bot1 bot2 - bot
    left1 mid1 right1 left2 mid2 right2 - arm
  )

  (:init
    (= (weight item16) 2)
    (= (weight item15) 1)
    (= (weight item14) 1)
    (= (weight item13) 2)
    (= (weight item12) 1)
    (= (weight item11) 1)
    (= (weight item10) 3)
    (= (weight item9) 1)
    (= (weight item8) 3)
    (= (weight item7) 1)
    (= (weight item6) 1)
    (= (weight item5) 1)
    (= (weight item4) 1)
    (= (weight item3) 2)
    (= (weight item2) 1)
    (= (weight item1) 3)
    (= (current_load bot1) 0)
    (= (load_limit bot1) 5)
    (= (current_load bot2) 0)
    (= (load_limit bot2) 5)
    (= (cost) 0)

    (at item16 rooma)
    (at item15 rooma)
    (at item14 roomb)
    (at item13 rooma)
    (at item12 roomb)
    (at item11 rooma)
    (at item10 rooma)
    (at item9 roomb)
    (at item8 rooma)
    (at item7 roomb)
    (at item6 rooma)
    (at item5 rooma)
    (at item4 rooma)
    (at item3 roomb)
    (at item2 roomb)
    (at item1 roomb)
    (at-bot bot1 rooma)
    (at-bot bot2 rooma)
    (free left1)
    (free mid1)
    (free right1)
    (free left2)
    (free mid2)
    (free right2)
    (mount left1 bot1)
    (mount mid1 bot1)
    (mount right1 bot1)
    (mount left2 bot2)
    (mount mid2 bot2)
    (mount right2 bot2)
    (door rooma roomb)
    (door roomb roomc)
    (door roomc roomd)
    (door roomd roome)
    (door roome rooma)
  )

  (:goal (and
    (at item16 roomd)
    (at item15 roomc)
    (at item14 roomd)
    (at item13 roomd)
    (at item12 roome)
    (at item11 roomd)
    (at item10 roomc)
    (at item9 roome)
    (at item8 roomc)
    (at item7 roomd)
    (at item6 roomd)
    (at item5 roomc)
    (at item4 roomc)
    (at item3 roomd)
    (at item2 roomd)
    (at item1 roomd)
  ))

  (:metric minimize (cost))
)
