(define (problem delivery-generated-9)
  (:domain delivery)
  (:objects
    rooma roomb roomc roomd - room
    item17 item16 item15 item14 item13 item12 item11 item10 item9 item8 item7 item6 item5 item4 item3 item2 item1 - item
    bot1 bot2 - bot
    left1 mid1 right1 left2 mid2 right2 - arm
  )

  (:init
    (= (weight item17) 2)
    (= (weight item16) 2)
    (= (weight item15) 1)
    (= (weight item14) 3)
    (= (weight item13) 2)
    (= (weight item12) 1)
    (= (weight item11) 1)
    (= (weight item10) 1)
    (= (weight item9) 3)
    (= (weight item8) 1)
    (= (weight item7) 1)
    (= (weight item6) 3)
    (= (weight item5) 3)
    (= (weight item4) 2)
    (= (weight item3) 2)
    (= (weight item2) 3)
    (= (weight item1) 3)
    (= (current_load bot1) 0)
    (= (load_limit bot1) 5)
    (= (current_load bot2) 0)
    (= (load_limit bot2) 5)
    (= (cost) 0)

    (at item17 rooma)
    (at item16 roomb)
    (at item15 rooma)
    (at item14 roomb)
    (at item13 rooma)
    (at item12 rooma)
    (at item11 rooma)
    (at item10 roomb)
    (at item9 roomb)
    (at item8 rooma)
    (at item7 roomb)
    (at item6 rooma)
    (at item5 roomb)
    (at item4 roomb)
    (at item3 roomb)
    (at item2 rooma)
    (at item1 rooma)
    (at-bot bot1 rooma)
    (at-bot bot2 rooma)
    (free left1)
    (free mid1)
    (free right1)
    (free left2)
    (free mid2)
    (free right2)
    (mount left1 bot1)
    (mount mid1 bot1)
    (mount right1 bot1)
    (mount left2 bot2)
    (mount mid2 bot2)
    (mount right2 bot2)
    (door rooma roomb)
    (door roomb rooma)
    (door rooma roomc)
    (door roomc rooma)
    (door roomd roomb)
    (door roomb roomd)
    (door roomd roomc)
    (door roomc roomd)
  )

  (:goal (and
    (at item17 roomc)
    (at item16 roomc)
    (at item15 roomc)
    (at item14 roomc)
    (at item13 roomc)
    (at item12 roomc)
    (at item11 roomc)
    (at item10 roomc)
    (at item9 rooma)
    (at item8 roomb)
    (at item7 rooma)
    (at item6 roomc)
    (at item5 roomd)
    (at item4 roomc)
    (at item3 roomc)
    (at item2 roomb)
    (at item1 roomb)
  ))

  (:metric minimize (cost))
)
